### ISSUE TITLE
Print unwanted slide data

### ISSUE THREAD

**Issue by maucejo** [McShelby/reveal-pdfexport#1]
Dear Sören,

First of all, thank you for this very useful plugin. However, I am facing a problem related to the use of PDFExport with the simple menu plugin. Actually, when I use PDFExport the menu appears on all slides, even on those for which the menubar is hidden.
I don't know whether the problem comes from the PDFExport plugin or the simple menu plugin.

For the sake of completeness, I am using reveal.js v4.3.1.

Thank you for your help !

**Comment by McShelby** [comment]
Pleae give a link to the "simple menu" plugin and assert that PDF Export is okay when only the "simple menu" plugin is active by [adding a `?print-pdf` to your URL](https://revealjs.com/pdf-export/).

**Comment by maucejo** [comment]
Thank you for your answer. I think I finally find the problem. It is related to the simple menu plugin. I don't figure out why, but it is seems that it does not work properly with the 'slideNumber' option in Reveal.initialize. When I remove this option, evereything works smoothly.

I will post an issue on the GitHub of the simple menu plugin.

Thank you!
